window.onload=function(){
	new Vue({
		el:'body',
		data:{
			msgData:[
			{
				title:'node.js入门的一些小技巧',
				content:'前端开发到底要不要学node.js，学习了它会有怎样的提高',
				time:'2017-3-16',
				href:'#'
			},
			{
				title:'关于webpack打包的一些注意事项',
				content:'网上很多的webpack的教程发现很多都是1.几版本，对于现在2.0使用起来有很大不同',
				time:'2017-3-18',
				href:'https://github.com/kodaline-w/Artical/blob/master/webpack%E6%89%93%E5%8C%85.mdown'
			},
			{
				title:'geihub如何建立个人博客',
				content:'前端开发到底要不要学node.js，学习了它会有怎样的提高',
				time:'2017-4-10',
				href:'#'
			},
			{
				title:'node.js入门的一些小技巧',
				content:'使用geihub建立博客对于很多人来说有很大帮助',
				time:'2017-4-15',
				href:'#'
			},
			{
				title:'ES6小入门',
				content:'随着时间推移，ES6马上要成了标配',
				time:'2017-4-19',
				href:'https://github.com/kodaline-w/Artical/blob/master/ES6%E5%85%A5%E9%97%A8.mdown'
			}]
		}
	})
}